name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 20.x, 21.x ]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable caching for npm packages
          
      - run: npm ci  # Use npm ci for faster and more reliable installs

      - run: npm run build

      - run: npm test  # Simplified command for running tests

      - name: Upload build artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: dist/
